project:
  type: website
  output-dir: docs

website:
  title: "Developing Software Together"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: preparation.qmd
        text: "Preparation"
      - href: presentation.qmd
        text: "Let's begin!"
      - text: "Materiales"
        menu:
          - href: materials.qmd
            text: "Working with RStudio"
          - href: materials_command_line.qmd
            text: "Working from the command line"

format:
  html:
    theme: sandstone
    toc: true

editor: visual
